## Question 4.2
Create 3 random matrices and compute their inverses, if they exist

In [16]:
## Run if necessary
pip install -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 65.6 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [ ]:
## Imports
import numpy as np

In [13]:
## Code for matrix A
matrix = [[1, 2, 3], [4, 5, -4], [-3, -2, -1]]

matrix_np = np.array(matrix)

print("For matrix A: ")
print(matrix_np)
try:
    inverse = np.linalg.inv(matrix_np)
    print("Inverse found:")
    print(inverse)

    identity = np.round((inverse @ matrix_np), 2)
    print("Proof of inverse: ")
    print(identity)
except np.linalg.LinAlgError:
    print("No inverse found")

For matrix A: 
[[ 1  2  3]
 [ 4  5 -4]
 [-3 -2 -1]]
Inverse found:
[[-0.325 -0.1   -0.575]
 [ 0.4    0.2    0.4  ]
 [ 0.175 -0.1   -0.075]]
Proof of inverse: 
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [14]:
## Code for matrix B
matrix = [[9, 2, -4], [-1, 8, 3], [5, 5, 5]]

matrix_np = np.array(matrix)

print("For matrix B: ")
print(matrix_np)
try:
    inverse = np.linalg.inv(matrix_np)
    print("Inverse found:")
    print(inverse)

    identity = np.round((inverse @ matrix_np), 2)
    print("Proof of inverse: ")
    print(identity)
except np.linalg.LinAlgError:
    print("No inverse found")

For matrix B: 
[[ 9  2 -4]
 [-1  8  3]
 [ 5  5  5]]
Inverse found:
[[ 0.05617978 -0.06741573  0.08539326]
 [ 0.04494382  0.14606742 -0.05168539]
 [-0.1011236  -0.07865169  0.16629213]]
Proof of inverse: 
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [15]:
## Code for matrix C
matrix = [[6, 6, 6], [6, 6, 6], [6, 6, 6]]

matrix_np = np.array(matrix)

print("For matrix C: ")
print(matrix_np)
try:
    inverse = np.linalg.inv(matrix_np)
    print("Inverse found:")
    print(inverse)

    identity = np.round((inverse @ matrix_np), 2)
    print("Proof of inverse: ")
    print(identity)
except np.linalg.LinAlgError:
    print("No inverse found")

For matrix C: 
[[6 6 6]
 [6 6 6]
 [6 6 6]]
No inverse found
